name: Check environment secret hash

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: "Environment secret (fixed choices)"
        type: choice
        options:
          - LITE_EMAIL_RECIPIENTS
          - BUSINESS_EMAIL_RECIPIENTS
          - INTERNAL_EMAIL_RECIPIENTS
          - TRIAL_EMAIL_RECIPIENTS
        required: true
        default: TRIAL_EMAIL_RECIPIENTS
      env_name:
        description: "Environment name"
        type: string
        required: true
        default: production

jobs:
  show:
    environment: ${{ inputs.env_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Compute and print safe info
        id: inspect
        # 動的インデックスを使わず、4つを固定参照で条件分岐
        env:
          SECRET_NAME: ${{ inputs.secret_name }}
          SECRET_VALUE:
            ${{ inputs.secret_name == 'LITE_EMAIL_RECIPIENTS' && secrets.LITE_EMAIL_RECIPIENTS
            || inputs.secret_name == 'BUSINESS_EMAIL_RECIPIENTS' && secrets.BUSINESS_EMAIL_RECIPIENTS
            || inputs.secret_name == 'INTERNAL_EMAIL_RECIPIENTS' && secrets.INTERNAL_EMAIL_RECIPIENTS
            || inputs.secret_name == 'TRIAL_EMAIL_RECIPIENTS' && secrets.TRIAL_EMAIL_RECIPIENTS
            || '' }}
        shell: bash
        run: |
          set -euo pipefail

          # 値を出力しない（長さ/ハッシュ/件数のみ）
          LEN=${#SECRET_VALUE}
          HASH=$(printf '%s' "$SECRET_VALUE" | sha256sum | awk '{print $1}')

          COUNT=0
          if [ "$LEN" -gt 0 ]; then
            TRIMMED=$(printf '%s' "$SECRET_VALUE" | tr -d ' \n\r\t')
            if [ -n "$TRIMMED" ]; then
              COUNT=$(( $(awk -v s="$TRIMMED" 'BEGIN{n=split(s,a,","); print n}') ))
            fi
          fi

          echo "Secret name     : $SECRET_NAME"
          echo "Environment     : ${{ inputs.env_name }}"
          echo "Length (bytes)  : $LEN"
          echo "SHA256          : $HASH"
          echo "CSV item count  : $COUNT"

          echo "len=$LEN"   >> "$GITHUB_OUTPUT"
          echo "hash=$HASH" >> "$GITHUB_OUTPUT"
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
