name: Export today's Myanmar articles CSV (MMT) and mail

on:
  schedule:
    - cron: "0 15 * * *" # ミャンマー時間 21:30（UTC+6:30）
  workflow_dispatch: {}

jobs:
  prod:
    # main ブランチでのスケジュール実行 or 手動実行のみ
    if: (github.event_name == 'schedule' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    name: Run (production / main)
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: export-today-csv-prod
      cancel-in-progress: false
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml python-dateutil google-genai \
                      google-api-python-client google-auth-httplib2 google-auth \
                      cloudscraper curl-cffi brotli brotlicffi

      - name: Run exporter (MMT today)
        env:
          # ===== Gemini (production) =====
          GEMINI_API_SUMMARY_KEY: ${{ secrets.GEMINI_API_EXPORT_SUMMARY_KEY }}
          GEMINI_API_DEDUPE_KEY: ${{ secrets.GEMINI_API_EXPORT_DEDUPE_KEY }}
          GEMINI_REQS_PER_MIN: "9"
          GEMINI_MIN_INTERVAL_SEC: "2.0"
          GEMINI_JITTER_SEC: "0.3"
          GEMINI_BATCH_SIZE: "100"
          # ===== Gmail (shared) =====
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          CSV_EMAIL_RECIPIENTS: ${{ secrets.CSV_EMAIL_RECIPIENTS }}
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
          PYTHONUTF8: "1"
          PYTHONIOENCODING: "UTF-8"
        run: |
          python export_today_articles_to_csv_and_mail.py \
            --out today_MMT.csv --batch-size 100 --rpm 9 --min-interval 2.0 --jitter 0.3

      - name: Post-run cleanup (in case)
        if: always()
        run: |
          rm -f today_MMT.csv || true

  dev:
    # develop ブランチの手動実行のみ
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/develop'
    name: Run (development / develop)
    runs-on: ubuntu-latest
    environment: development
    concurrency:
      group: export-today-csv-dev
      cancel-in-progress: true # 手動は新しい実行を優先
    steps:
      - name: Checkout (develop)
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml python-dateutil google-genai \
                      google-api-python-client google-auth-httplib2 google-auth \
                      cloudscraper curl-cffi brotli brotlicffi

      - name: Run exporter (MMT today)
        env:
          # ===== Gemini (development/test keys) =====
          GEMINI_API_SUMMARY_KEY: ${{ secrets.GEMINI_API_TEST_SUMMARY_KEY }}
          GEMINI_API_DEDUPE_KEY: ${{ secrets.GEMINI_API_TEST_DEDUPE_KEY }}
          GEMINI_REQS_PER_MIN: "9"
          GEMINI_MIN_INTERVAL_SEC: "2.0"
          GEMINI_JITTER_SEC: "0.3"
          GEMINI_BATCH_SIZE: "100"
          # ===== Gmail (shared) =====
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          CSV_EMAIL_RECIPIENTS: ${{ secrets.CSV_EMAIL_RECIPIENTS }}
          LANG: C.UTF-8
          LC_ALL: C.UTF-8
          PYTHONUTF8: "1"
          PYTHONIOENCODING: "UTF-8"
        run: |
          python export_today_articles_to_csv_and_mail.py \
            --out today_MMT.csv --batch-size 100 --rpm 9 --min-interval 2.0 --jitter 0.3

      - name: Upload CSV artifact on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: today_MMT.csv
          path: today_MMT.csv
          retention-days: 1

      - name: Post-run cleanup (in case)
        if: always()
        run: |
          rm -f today_MMT.csv || true
