name: Dump ENV Secrets by Environment (encrypted)

on:
  workflow_dispatch:
    inputs:
      age_recipient:
        description: "age recipient (public key starting with age1...)"
        required: true
        type: string
      target_env:
        description: "Which environment's secrets to dump"
        required: true
        type: choice
        options:
          - production
          - development
          - both

permissions:
  contents: read

jobs:
  dump-production:
    if: ${{ github.event.inputs.target_env == 'production' || github.event.inputs.target_env == 'both' }}
    name: Dump (production)
    runs-on: ubuntu-latest
    # ★ Environment を指定すると、その Environment に紐づく Secrets が参照可能になります
    environment: production
    env:
      INTERNAL_EMAIL_RECIPIENTS: ${{ secrets.INTERNAL_EMAIL_RECIPIENTS }}
      LITE_EMAIL_RECIPIENTS: ${{ secrets.LITE_EMAIL_RECIPIENTS }}
      BUSINESS_EMAIL_RECIPIENTS: ${{ secrets.BUSINESS_EMAIL_RECIPIENTS }}
      TRIAL_EMAIL_RECIPIENTS: ${{ secrets.TRIAL_EMAIL_RECIPIENTS }}
    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age

      - name: Write secrets to file (NO LOG)
        shell: bash
        run: |
          set -euo pipefail
          set +x  # 値のログ出力を抑止
          {
            printf 'ENVIRONMENT=%s\n' "production"
            printf 'INTERNAL_EMAIL_RECIPIENTS=%s\n' "${INTERNAL_EMAIL_RECIPIENTS:-}"
            printf 'LITE_EMAIL_RECIPIENTS=%s\n'     "${LITE_EMAIL_RECIPIENTS:-}"
            printf 'BUSINESS_EMAIL_RECIPIENTS=%s\n' "${BUSINESS_EMAIL_RECIPIENTS:-}"
            printf 'TRIAL_EMAIL_RECIPIENTS=%s\n'    "${TRIAL_EMAIL_RECIPIENTS:-}"
          } > secrets.production.txt
          bytes=$(wc -c < secrets.production.txt | tr -d ' ')
          echo "Prepared secrets.production.txt (${bytes} bytes)"

      - name: Encrypt with age recipient
        shell: bash
        run: |
          set -euo pipefail
          set +x
          AGE_RECIPIENT="${{ github.event.inputs.age_recipient }}"
          test -n "$AGE_RECIPIENT"
          age -r "$AGE_RECIPIENT" -o secrets.production.txt.age secrets.production.txt
          shred -u secrets.production.txt

      - name: Upload encrypted artifact (production)
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-production
          path: secrets.production.txt.age
          if-no-files-found: error
          retention-days: 1

  dump-development:
    if: ${{ github.event.inputs.target_env == 'development' || github.event.inputs.target_env == 'both' }}
    name: Dump (development)
    runs-on: ubuntu-latest
    environment: development
    env:
      INTERNAL_EMAIL_RECIPIENTS: ${{ secrets.INTERNAL_EMAIL_RECIPIENTS }}
      LITE_EMAIL_RECIPIENTS: ${{ secrets.LITE_EMAIL_RECIPIENTS }}
      BUSINESS_EMAIL_RECIPIENTS: ${{ secrets.BUSINESS_EMAIL_RECIPIENTS }}
      TRIAL_EMAIL_RECIPIENTS: ${{ secrets.TRIAL_EMAIL_RECIPIENTS }}
    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age

      - name: Write secrets to file (NO LOG)
        shell: bash
        run: |
          set -euo pipefail
          set +x
          {
            printf 'ENVIRONMENT=%s\n' "development"
            printf 'INTERNAL_EMAIL_RECIPIENTS=%s\n' "${INTERNAL_EMAIL_RECIPIENTS:-}"
            printf 'LITE_EMAIL_RECIPIENTS=%s\n'     "${LITE_EMAIL_RECIPIENTS:-}"
            printf 'BUSINESS_EMAIL_RECIPIENTS=%s\n' "${BUSINESS_EMAIL_RECIPIENTS:-}"
            printf 'TRIAL_EMAIL_RECIPIENTS=%s\n'    "${TRIAL_EMAIL_RECIPIENTS:-}"
          } > secrets.development.txt
          bytes=$(wc -c < secrets.development.txt | tr -d ' ')
          echo "Prepared secrets.development.txt (${bytes} bytes)"

      - name: Encrypt with age recipient
        shell: bash
        run: |
          set -euo pipefail
          set +x
          AGE_RECIPIENT="${{ github.event.inputs.age_recipient }}"
          test -n "$AGE_RECIPIENT"
          age -r "$AGE_RECIPIENT" -o secrets.development.txt.age secrets.development.txt
          shred -u secrets.development.txt

      - name: Upload encrypted artifact (development)
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-development
          path: secrets.development.txt.age
          if-no-files-found: error
          retention-days: 1
